### ISSUE TITLE
Getting errors with concatenation

### ISSUE THREAD

**Issue by bdanzer** [megahertz/twigjs-loader#4]
If I use this bit of code that I know works in the PHP version:

`{% include '@dp/section-parts/icons/' ~ layout.icons_layout ~ '.twig' %}`

I will get this error:

` WARNING  Compiled with 1 warnings                                                           14:30:56

 warning  in ./src/templates/dp-sections/icon.twig

Module build failed (from ./node_modules/twigjs-loader/index.js):
TypeError: Cannot read property 'indexOf' of undefined
    at Resolver.parse (/Users/user/dp/dp-vue-wrapper/node_modules/enhanced-resolve/lib/Resolver.js:301:31)
    at resolver.getHook.tapAsync (/Users/user/dp/dp-vue-wrapper/node_modules/enhanced-resolve/lib/ParsePlugin.js:18:29)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/user/dp/dp-vue-wrapper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/user/dp/dp-vue-wrapper/node_modules/enhanced-resolve/lib/Resolver.js:282:16)
    at resolver.getHook.tapAsync (/Users/user/dp/dp-vue-wrapper/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:36:14)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/user/dp/dp-vue-wrapper/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/user/dp/dp-vue-wrapper/node_modules/enhanced-resolve/lib/Resolver.js:282:16)
    at Resolver.resolve (/Users/user/dp/dp-vue-wrapper/node_modules/enhanced-resolve/lib/Resolver.js:170:15)
    at Object.resolve (/Users/user/dp/dp-vue-wrapper/node_modules/webpack/lib/NormalModule.js:197:14)
    at Promise (/Users/user/dp/dp-vue-wrapper/node_modules/twigjs-loader/index.js:124:15)
    at new Promise (<anonymous>)
    at resolveModule (/Users/user/dp/dp-vue-wrapper/node_modules/twigjs-loader/index.js:123:10)
    at processDependency (/Users/user/dp/dp-vue-wrapper/node_modules/twigjs-loader/index.js:51:32)
    at Array.map (<anonymous>)
    at each (/Users/user/dp/dp-vue-wrapper/node_modules/twigjs-loader/index.js:101:26)
    at processToken (/Users/user/dp/dp-vue-wrapper/node_modules/twigjs-loader/index.js:76:15)

 @ ./src/templates/dp-sections sync ^\.\/.*\.twig$
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js&
 @ ./src/components/HelloWorld.vue?vue&type=script&lang=js&
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.134:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js`

**Comment by megahertz** [comment]
Sorry, but I'm not going to add support for complex include blocks.
